apiVersion: v1
kind: Service
metadata:
  name: {{ include "switchblade.fullname" . }}
  labels:
    {{- include "switchblade.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "switchblade.selectorLabels" . | nindent 4 }}
